application: ramdonmarca
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /new
  script: main.application
  login: admin
  secure: optional

- url: /edit
  script: main.application
  login: admin
  secure: optional

- url: /destroy
  script: main.application
  login: admin
  secure: optional

- url: /stylesheets
  mime_type: text/css
  static_dir: static/css

- url: /js
  mime_type: text/javascript
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /.*
  script: main.application
  secure: optional

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest